***

*Course:* [Math 535](https://people.math.wisc.edu/~roch/mmids/) - Mathematical Methods in Data Science (MMiDS)  
*Chapter:* 1-Introduction   
*Author:* [Sebastien Roch](https://people.math.wisc.edu/~roch/), Department of Mathematics, University of Wisconsin-Madison (with the help of ChatGPT 4)
*Updated:* Jan 27, 2024   
*Copyright:* &copy; 2024 Sebastien Roch

***

## Auto-quizzes

This notebook generates automated quizzes as well as the answers. Set the `seed` to any integer to produce unique quizzes.

In [1]:
# Python 3
import numpy as np
from numpy import linalg as LA
from numpy.random import default_rng

In [2]:
# Set the `seed` to any integer
seed=535

In [3]:
rng = default_rng(seed)

**AQ1.1**  

***

*Use the following code to generate the quiz questions. You should be able to answer them by hand -- that is, without the help of numerical computation.*

***

This exercise concerns $k$-means clustering with $k = 2$ clusters. To be consistent with Python indexing, we will index the clusters and vectors starting at 0. Consider the following input vectors:

In [4]:
x0 = np.array([0., 0., 0.])
x1 = np.array([0., 1., 0.])
x2 = np.array([0., 0., 1.])
x3 = np.array([1., 1., 0.])
x4 = np.array([1., 0., 1.])
x5 = np.array([1., 1., 1.])
print(f'x0 =',x0)
print(f'x1 =',x1)
print(f'x2 =',x2)
print(f'x3 =',x3)
print(f'x4 =',x4)
print(f'x5 =',x5)

x0 = [0. 0. 0.]
x1 = [0. 1. 0.]
x2 = [0. 0. 1.]
x3 = [1. 1. 0.]
x4 = [1. 0. 1.]
x5 = [1. 1. 1.]


Consider the following representative vectors:

In [5]:
mu0 = np.array([-1.])
random_part0 = np.random.choice([0, 1], 2)
mu0 = np.concatenate([mu0, random_part0])
mu1 = np.array([2.])
random_part1 = np.random.choice([0, 1], 2)
mu1 = np.concatenate([mu1, random_part1])
permuted_indices = np.random.permutation(len(mu0))
mu0 = mu0[permuted_indices]
mu1 = mu1[permuted_indices]
print('mu0 =',mu0)
print('mu1 =',mu1)

mu0 = [-1.  0.  0.]
mu1 = [2. 0. 1.]


and the following clusters:

In [6]:
original_set = np.array([0, 1, 2, 3, 4, 5])
np.random.shuffle(original_set)
split_point = np.random.randint(1, len(original_set))
C0 = original_set[:split_point]
C1 = original_set[split_point:]
print('C0 =', C0)
print('C1 =', C1)

C0 = [1]
C1 = [3 0 4 5 2]


a) For the fixed clusters `C0` and `C1`, compute the optimal representatives `mu0_new` and `mu1_new`.

b) For the fixed representatives `mu0` and `mu1`, compute the optimal clustering `C0_new` and `C1_new`.

c) For the solution in b), compute the $k$-means objective function.

d) For the solution in b), write down the matrix form of the input and of the solution, that is, the matrices `X`, `Z`, `U` in the notes.

***

*Use the following code to generate the answers.*

***

In [7]:
# a)

k = 2
X = np.stack((x0,x1,x2,x3,x4,x5))

mu0_new = np.sum(X[C0,:],axis=0) / len(C0)
mu1_new = np.sum(X[C1,:],axis=0) / len(C1)

print('mu0_new =', mu0_new)
print('mu1_new =', mu1_new)

mu0_new = [0. 1. 0.]
mu1_new = [0.6 0.4 0.6]


In [8]:
# b)

(n,d) = X.shape
U = np.stack((mu0,mu1))
dist = np.zeros(n)
C0_new = []
C1_new = []
for j in range(n):
    dist_to_i = np.array([LA.norm(X[j,:] - U[i,:]) for i in range(k)])
    if np.argmin(dist_to_i) == 0:
        C0_new.append(j)
        dist[j] = dist_to_i[0]
    else:
        C1_new.append(j)
        dist[j] = dist_to_i[1]    

print('C0_new =', C0_new)
print('C1_new =', C1_new)

C0_new = [0, 1, 2]
C1_new = [3, 4, 5]


In [9]:
# c)

G = np.sum(dist ** 2)

print('G =', G)

G = 11.0


In [10]:
# d)

Z= np.zeros((len(original_set), 2), dtype=int)

for i in C0_new:
    Z[i, 0] = 1
for i in C1_new:
    Z[i, 1] = 1

print('X =', X)
print('Z =', Z)
print('U =', U)

X = [[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [1. 1. 1.]]
Z = [[1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
U = [[-1.  0.  0.]
 [ 2.  0.  1.]]


$\lhd$